//@ts-nocheck
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatType } from "three";
import { FloatingNav } from "@/components/ui/Navbar";

 const navItems = [
  { name: "Play", link: "#about" },
  { name: "Visualize", link: "#projects" },
  { name: "Code", link: "#testimonials" },
  { name: "Profile", link: "#contact" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<nav className=" shadow-md p-4 flex justify-between items-center">
  <div className="text-xl font-bold">CodeCrux</div>
  <ul className="hidden md:flex space-x-6">
    <li><a href="https://codecrux-hero.vercel.app/" className="hover:text-gray-600">Home</a></li>
    <li><a href="https://codecrux-profile.vercel.app/" className="hover:text-gray-600">Profile</a></li>
    <li><a href="http://localhost:3000/AlgorithmVisualizer/AlgorithmVisualizer" className="hover:text-gray-600">Visualize</a></li>
    <li><a href="https://codecrux-community.vercel.app/" className="hover:text-gray-600">Community</a></li>
  </ul>
  <button className="md:hidden text-gray-600">☰</button>
</nav>
        {children}
      </body>
    </html>
  );
}
